### ISSUE TITLE
lets have an anything goes social contract made explicit and call this DaoWars!

### ISSUE THREAD

**Issue by ebuchman** [ethereumclassic/README#1]
some of us have been talking about the idea for sometime of carrying forward the noforkethereum and letting there be an explicit "anything goes" social contract. the name DaoWars or DaoCraft are also pretty catchy.

I very strongly support the existence of both chains and I think they would be a major boon to the community.

**Comment by arvicco** [comment]
You got it right - Ethereum Classic has explicit neutrality guarantee as per: https://medium.com/@bit_novosti/a-crypto-decentralist-manifesto-6ba1fa0b9ede

What's happening on smart contract/application level is not platform developer's business.

**Comment by arvicco** [comment]
I think DaoWars is a bit narrow though. Implications of principled blockchain neutrality are much wider than theDAO.

**Comment by whatisgravity** [comment]
I fully support this neutral stance, if any assistance is needed in maintaining the original chain I would like to assist.

**Comment by arvicco** [comment]
Naming and branding discussion: https://trello.com/b/ziFiVzAc/etc-branding-identity
