### ISSUE TITLE
Mining Consolidation

### ISSUE THREAD

**Issue by whatisgravity** [ethereumclassic/README#11]
We need to address mining consolidation before it becomes a problem. 

We need ensure there is at least 2-3 pools with the weight distributed across them.

**Comment by arvicco** [comment]
I don't see it's pressing. Two pools are kind of OK for now, with solo mining possible again. Of course, anyone is welcome to start new pool, and we'll support and promote it everywhere just the same. 

So, exchange presence is my bigger focus right now.

**Comment by whatisgravity** [comment]
I believe this will help with exchange adoption, if we can show the larger exchanges our network is not easily attacked by a single pool operator they will have more reason to trust the network. I believe overall mining power and this this problem the primary reasoning behind waiting .

In the unlikely event an attack did occur, the target would be the exchanges.

You have done an amazing job with the pool you setup.

**Comment by arvicco** [comment]
Multiple ETC pools now, not an issue any longer: http://etherx.com/pools
