### ISSUE TITLE
Preparing for a 51% attack

### ISSUE THREAD

**Issue by whatisgravity** [ethereumclassic/README#14]
I honestly think that the threats are empty, given the amount of money it would take to sustain an attack. 

I don't think a double spend would be attempted since that would allow us to easily take legal action against them. I think the attack would be a DOS where they only accept empty blocks, while rejecting all transactions.

Since we have essentially 1 service using our network this would not do too much damage, and it would be very costly to operate so that makes it unlikely to occur especially for a long period of time.

In the event they are able to sustain this type of DOS for a long time I would like to be ready.

In the event it does occur, we want to be able to quickly react. I will begin writing and testing a soft fork we can apply to the http://ethc.epool.io 

My initial idea is to find a way to ignore the a chain with multiple empty blocks or tracking the head of the attack based on a configured attack base block. Tracking by signature seems futile since they could change it on the attacker realizes we are ignoring their blocks based on that. Foing this filtering in an efficient way will be the difficult part. 

 If anyone has any suggestions I will be checking this regularly to discuss the topic. 

Thankfully hive (https://github.com/karalabe/hive) was recently published, I have it setup and this seems like a good way to find out how well it can be used to run simulations. I suggest anyone interested in working on this problem use this.

**Comment by whatisgravity** [comment]
With the attack surface of our network evolving this problem becomes more complex, I think it is still worth investing time into testing different ways this problem can be mitigated. I have begun some work but it was under the context of the previous state of the network described above.

It would be best to be prepared for an attack like this before it occurs, so we can determine a solution without being under pressure to react immediately.

**Comment by arvicco** [comment]
So far, the threat of 51% did not materialize. ETC mining has now diversified into multiple pools, so we don't depend on one pool for security.
