### ISSUE TITLE
Changing POW to Equihash

### ISSUE THREAD

**Issue by HostFat** [ethereumclassic/README#15]
Maybe you should change the POW to Equihash

There is something here already:
https://github.com/khovratovich/equihash
https://github.com/zcash/zcash

**Comment by Seccour** [comment]
We should wait and not change anything for now. Except the port number as proposed on Reddit so we don't use the same as Ethereum.

**Comment by HostFat** [comment]
It's good to survive to 51% attacks.

**Comment by Seccour** [comment]
We're getting more and more hashpower, so i don't think it will be a problem. Our priority should be to get more pools and allocate all this hashing power into different pool because right now most of ETHC hashrate come from epool and that's kind of bad and more scary than a 51% attack.

**Comment by whatisgravity** [comment]
If you want to change the hashing algorithm it would be better to start a new fork at this stage. Doing this would split the community again. 

Also I recommend you don't change any port numbers, you can change them in your configuration if its difficult to use both. Changing the p2p port will remove our ability to interlop with existing clients on the network running older ETH software.

**Comment by arvicco** [comment]
Anyone is welcome to create ECIP (Ethereum Classic Improvement Proposal): https://github.com/ethereumproject/ECIPs/issues/new
