### ISSUE TITLE
Developers

### ISSUE THREAD

**Issue by CharlesHoskinson** [ethereumclassic/README#16]
Glad to see the fork happen thereby preserving the principles of the original system. I'd love to help you guys get established and potentially contribute some full time developers to ensure the code is well maintained. Could the project lead email me at Charles.Hoskinson@iohk.io

**Comment by arvicco** [comment]
Hello, Charles!

Thanks for your interest, and welcome (again ;) to Ethereum!

Classic dev effort is focused around ethereumproject org, ethereumclassic org is more focused on non-dev issues.

Dev org membership/coordination is done here: https://github.com/ethereumproject/go-ethereum/issues/1. Lead dev is @whatisgravity, please get in touch with him or he will.

**Comment by whatisgravity** [comment]
Thanks for reaching out, we can definitely use more developers volunteering to maintain the project.

**Comment by CharlesHoskinson** [comment]
@whatisgravity I might be able to contribute up to three full time developers and a cryptographer for at least a year to the project as a donation to the project. I have a fairly well staffed development company and we are always looking for interesting projects. Add me on Skype Charles_Hoskinson. I'd love to chat about your roadmap and philosophy.

**Comment by whatisgravity** [comment]
@CharlesHoskinson I apologize I have not been able to reach out to you yet, I promise I will have time to have a direct discussion on this topic soon and my inability to do so is not that I don't feel this is important. 

In the meantime, do you have any specific plan with those allocated resources? Are you interested in contributing to a specific client like go-ethereum, starting a new client or specifically tackling the problem of proof of stake migration? Knowing this may be able to help me determine how we can collaborate efforts between volunteers.

**Comment by matthewjamesr** [comment]
@whatisgravity I think coordination is slightly starting to get out of hand between this namespace and the other. Once we merge things might cool a little but I think it may be a great idea to create a basic tasking webapp for us to organize better.

We could either do this custom via a very simple skeleton to start or make a open/public Trello board. Thoughts? I would be will to help out on this as well.

**Comment by whatisgravity** [comment]
I'm for it, even if we just experiment with it, it may help us better understand what exactly we need.

**Comment by arvicco** [comment]
Volunteers interested in joining ETC dev team should post to: https://github.com/ethereumproject/volunteer/issues/27
