### ISSUE TITLE
Does anyone make a website clone ethereum.org and update www.ethereumclassic.org 

### ISSUE THREAD

**Issue by soundbit** [ethereumclassic/README#17]
What I see now, it looks like a student work

**Comment by soundbit** [comment]
Ethereum classic for developer or speculation?

**Comment by soundbit** [comment]
When will the latest news? @arvicco if you're the coordinator, you must act quickly and decisively to the community believed in the project

**Comment by soundbit** [comment]
where i can see the roadmap? how the work with enthusiasts? Who are they?

**Comment by arvicco** [comment]
Yes, I wrote ETC "website" in markdown a week ago and posted it to Github pages via auto-gen. It's absolutely awful, and needs to be replaced asap. I have neither time nor skills for that. Interested to help?

**Comment by soundbit** [comment]
@arvicco да, я готов помочь с этим, напиши мне в телеграм, надо обсудить, как текущий контент будет вписываться в форк веб-морды ethereum.org telegram.me/abaev

**Comment by soundbit** [comment]
@arvicco я думаю надо подготовить манифест

**Comment by arvicco** [comment]
https://medium.com/@bit_novosti/a-crypto-decentralist-manifesto-6ba1fa0b9ede

**Comment by arvicco** [comment]
@soundbit Sorry, I don't use telegram. Slack?

**Comment by arvicco** [comment]
ethereumclassic.org
