### ISSUE TITLE
Transaction Nonce

### ISSUE THREAD

**Issue by whatisgravity** [ethereumclassic/README#18]
I want to clarify the situation since we have had a lot of people from the ETHF side calling for us to make changes, and I want to explain why its not only unnecessary for us, it would sabotage our chances at success. 

**What Should Have Happened**
ETHF already forked, however they failed to do it properly, they should have created a new *rule set* when they hard forked. As defined in the geth codebase:

    // RuleSet is an interface that defines the current rule set during the
    // execution of the EVM instructions (e.g. whether it's homestead)

They changed the way the EVM executes instructions by hard coding changes to the DAO contract. 

To illustrate, our expected response from certain executions relating to these contracts is now different on each network. 

Therefore, they should have created a new *rule set* for their changes. **If they had properly coded their fork, they could have avoided all the issues with relaying across both networks, in the same way we don't have to worry about Morden relaying to the live networks.** They have caused their own problems with their inability to understand the system as it exists. 

Since they have already severed their connection to existing clients, they lose nothing by finishing to properly do those changes and split the network by *rule set*. 

Expecting us to make this change, destroy our existing connection to old clients on the network is wrong. They forked, they have already destroyed their existing connection, so they don't lose anything by finishing the job and doing it properly but we would if we made changes.

**Why they insist we do it**

They want us to do it because they have disconnected themselves from all existing clients running old versions on the network, since we still connect to these clients it gives us a significant advantage, because while our active user base is still growing we are supported by all the older clients running. 

They could only propose we make the change from ignorance of the system or knowing this change would effectively cut us off from all these old clients making us weaker. 

**Overstating Relaying Issues**
Relaying issues are irrelevant once you split your tokens to different new addresses. If you keep your tokens separate or like me you migrate entirely to one network, you only have to do this once and you never have to worry about it again.

**What ETHF supporters fail to state is they have a bigger problem than we do in regards to the relay issue**, since some of their major contracts existed prior to the fork, it is not easy for them to split. However since essentially 100% of our contracts will be redeployed or deployed after the fork it does not affect us. 

Since the operators of these contracts have stated they are for ETHF and do not care about ETC then they should not care about the relay issues too.

**My proposed response**
I propose, we respond to their calls for us to make changes that would destroy our connection to older clients with counter proposal: 

*They should create a new rule set for their fork, stop trying to rewrite the rules, since it changes the way the EVM functions change your rule set.*

**Future position on similar updates**
I'm not claiming we should never make a change that would disconnect us from old clients, I'm just saying in this instance, with our network this new, it is not a wise move. 

In the future there may be a situation where we do want to make changes which would not allow connection with old clients but we should put it off for as long as we reasonably can. 

**Related Information**
That said, we still need volunteers to run dedicated nodes for bootstraping, you can find information how to volunteer on the github. I could run them all myself but I would prefer if we did this in a decentralized way and volunteers help balance the control over the network.

**Comment by whatisgravity** [comment]
If anyone has any differing opinions, I'm not suggesting my opinion overrides anyone else's, please share your opinions on the subject. 

If you have a differing view we can discuss it and come to a agreement on the topic.

**Comment by soundbit** [comment]
http://vessenes.com/do-not-mess-with-eth-classic-it-will-f-you-up/

**Comment by arvicco** [comment]
@whatisgravity I agree with your argumentation. For the ones forking off (leaving consensus), it stands to reason that they are liable to institute a clean split, and not expect to push the burden to the ones already in consensus.

I can see how pro-forkers could spin the issue into trying to intimidate Ethereum users into never even looking our way. But this is a short-sighted position and it comes to bite them in the ass both on security/responsibility grounds and if it becomes obvious that momentum is sufficient to put ETC in a position of a dominant chain. Than the tables will turn very quickly on them, especially once the knowledge about WHO is responsible for this mess spreads widely.

Another fast HF by the forked chain is the proper way to solve this issue, and it is in their best interest to do it sooner rather than later until it becomes a PR issue AGAINST them. To the pro-forkers who may read this: **"You know what is the right thing to do. Just do it now, or face the consequences of your inaction."**

**Comment by arvicco** [comment]
Further discussion of the issue: https://github.com/ethereumproject/ECIPs/issues/7
