### ISSUE TITLE
I'd like to help!(Website)

### ISSUE THREAD

**Issue by JohnDoe556** [ethereumclassic/README#19]
Hi, I would love to assist ETC with anything webrelated! Get in touch!

**Comment by whatisgravity** [comment]
I believe @arvicco is in control of the website, when they have time they may be able to inform you how you can help. 

How comfortable are you with web development? Are you comfortable contributing to a blockchain explorer or is your skills more design oriented? With additional information it may be easier to help guide you on how can contribute.
