### ISSUE TITLE
Need miner Claymore, for ETH + ETC mining

### ISSUE THREAD

**Issue by soundbit** [ethereumclassic/README#22]
This will attract new capacities and protect against attacks 51% 
Contact anyone with developer Claymore

**Comment by whatisgravity** [comment]
To clarify this is the miner that is capable of mining both chains at the same time?

**Comment by soundbit** [comment]
@whatisgravity yes it is possible?

**Comment by whatisgravity** [comment]
I do believe it is possible, but this is unfortunately outside my area of expertise, I do have some experience working with opencl but there are others who would have a better handle on how to approach this problem. I agree this is a very good avenue of research, it would probably warrant a section in the Volunteer readme of the developer group.

**Comment by arvicco** [comment]
ETC already supported by Claymore.
