### ISSUE TITLE
Twitter Account for Ethereum Classic and Dev Meet Ups @eth_classic

### ISSUE THREAD

**Issue by ChuckSRQ** [ethereumclassic/README#32]
I've started a twitter account for News &Information on Ethereum Classic. It can be found here. https://twitter.com/eth_classic

Information on future Developer Meet Ups will be posted as well.

**Comment by arvicco** [comment]
@ChuckSRQ Thanks for making it happen! Please announce this on Reddit as well.

(and I like how you play the angle of EF irresponsibly using replay attacks as a weapon against legacy chain)

**Comment by ProphetDaniel** [comment]
@ChuckSRQ , change link of the twitter to ethereumclassic.org, please.

**Comment by ProphetDaniel** [comment]
@ChuckSRQ , I would like to invite you to be an administrator of the Linkedin company`s account.

**Comment by ProphetDaniel** [comment]
@ChuckSRQ please update the image of the twitter account to one where ETC goes up and ETH goes down. That would be preferrable if possible.

**Comment by ChuckSRQ** [comment]
@ProphetDaniel Your requests have been accomplished. I do not have linkedin but thanks anyway.

**Comment by realcodywburns** [comment]
Seems as good an issue to bring this up on as any: we need to start coordinating social media teams to give a 'voice' to the classic community

Social Media coordination

 **Identify desirable outlets**
-     -Twitter
-     -youtube
-     -reddit
-     -stack
-     -facebok
-     -wechat
-     -meetup
-     -linkedin
-     -any other I may have missed
    
** Identify current account holders**
Find current holders of ethereum<sup>classic</sup> accounts and join or coordinate with them

 **Hootsuite(or similar) organization page to coordinate messaging**
Used to get a team on one page, scan social media, push messages

**Comment by ChuckSRQ** [comment]
@realcodywburns What are the advantages/disadvantage to using Hootesuite? Other than twitter and Meetup, Where else do we have significant presence on social media? 

Doesn't look like we have a page on Facebook that is being run effectively. I'm thinking of just starting one and connecting it to the twitter account @eth_classic if we don't get something soon.

**Comment by realcodywburns** [comment]
Hootsuite can allow you to monitor multiple media outlets at once for key words and topics, coordinate with a team on planning messages, and keeping track of past messages. Its a one and done approach, you can submit to facebook, twitter, linkedin, what ever all at once.

**Comment by ProphetDaniel** [comment]
I agree that we should try with Hootsuite to improve our social presence and unity.

**Comment by bart-w0** [comment]
I am against single point for monitoring all media outlets, because:
1. I hate when companies use it - I'm getting notifications from multiple sites about the same thing. I.e. I saw it on Twitter, I would prefer to not see the same thing later on FB and YT.
2. We should avoid such centralisation. Let different people manage different social media accounts and we will see which one will pick up.

**Comment by arvicco** [comment]
I think multiple accounts in the same media also ok, like 
Twitter: @eth_classic, @EthereumClassic

**Comment by BitBanksy** [comment]
@arvicco that would be confusing. Better one well kept channel
