### ISSUE TITLE
Whitepaper needed

### ISSUE THREAD

**Issue by ProphetDaniel** [ethereumclassic/README#33]
In my opinion we need a whitepaper written to address the core of Ethereum Classic. My suggestion is to offer a XBTfreelancer project then select best researcher/writter there to start this task.

**Comment by realcodywburns** [comment]
A white paper for the underlying technology or for the concept of a true crypto-anarchy based on the principles of immutably and free association?

**Comment by whatisgravity** [comment]
Being specific is important, it is hard for others to weigh in without a specific plan. realcodywburns question is important.

A white paper for the underlying technology is already done, and there is little gained from making modifications to it. However there may be a use of a white paper regarding our developing organization strategy. 

However, keep in mind, just because we choose to organize in this way does not preclude others from creating their own organizations and organizing a different way.

**Comment by realcodywburns** [comment]
I am actually quite pro anarchy in the Tim May context of things (http://groups.csail.mit.edu/mac/classes/6.805/articles/crypto/cypherpunks/may-crypto-manifesto.html) We are at a very unique point in crypto history where the 'ruling class' willingly left the original project and left it open to enjoy the freedom of anarchy. I think that any white paper should address this and deter any form of official 'governance'.

**Comment by realcodywburns** [comment]
If a technical paper is what your after we could appen a time line to highlight the diffrences in the core code. The most concisely i have seen it listed is: in order, from the most recent.

July 20, 2016: Ethereum Classic does not contain the irregular state change in block 1920000 that transferred Ether to a WithdrawDAO recovery contract.

**Comment by ProphetDaniel** [comment]
When I was creating the LinkedIn page, there was a scroll box to choose among several business sectors. Instead of choosing internet, the one currently chosen by forked Ethereum, I realized it wasn't just plain internet our business sector. With that in mind I selected Civic & Social Organization, I hope it was the best choice for representing the community.

Some hours later I saw more than once unanswered questions inside forums like: How does Ethereum Classic grow so fast? I realized that as an Ethereum Classic community member I should at least try to explain the phenomenon.

Democracy, criptography, anarchy freedom, blind justice, respect, growth oriented plurality of thoughts, technology advances for reaching the ultimate goal of improving society for a better place to live in the near future are among the ideas that I think are boosting this community and making it so appealing.

Then I asked myself where something like this has already happened in history. I didn't find an answer maybe due to my ignorance on the subject or maybe because it actually didn't happen. And if it still didn't happen we are probably making history and having the opportunity to give awesome examples for future generations.

So @realcodywburns and @whatisgravity fellows, I think a whitepaper representing deep research on the matter is welcome for increasing the conscience level of the community and for recording history.

**Comment by ChuckSRQ** [comment]
I think a white paper for Ethereum Classic should be modeled after the Declaration of Independence of the United States. http://www.archives.gov/exhibits/charters/declaration_transcript.html

We should firstly state that the Foundation through various public announcements and actions abandoned development of the Ethereum Classic chain.  That while we recognize the hard work, creation, and development of ETC by the Foundation up until block 192,000 and thank them for that, we make it crystal clear that through their actions, they have relinquished any type of governance and/or development of the Ethereum Classic Chain. We should declare that Ethereum Classic is Open Source software and in that light, a decentralized community has formed in place of the Centralized Ethereum Foundation to continue the development of the Classic Chain. 

We should state all the objections and grievances that we as a community had to the actions the Foundation and others took to the hacking of the DAO, the rushing of the soft fork, and the rushing of code for the hard fork. That when they neglected to include replay protection, they hoped to destroy the viabilty of the Ethereum Classic chain and no longer worked for it's betterment and success. We should also state the inaction and negligence of slock.it and the Foundation in not contacting traditional law enforcement to what they deemed a "theft." That in their actions, they went against many of the statements, announcements, and advertisements made to users and others of the nature and features of Ethereum and smart contracts. 

We should also state that we are not against hard forks for the purposes of updating or upgrading the technology behind the Ethereum Blockchain, only hard forks done in a manner which violates the immutability fungibilty,and the ledger of transactions. 

We should cite in our paper many of the visionaries and philosophical leaders that have lead the human race to a greater degree of freedom and understanding of markets. In this light, I will start a group in the Slack It group to form a writing group to present to the community a rough draft to receive feedback on improvement and changes.  

We should state an overall vision of decentralized governance for the Ethereum Classic chain and our opposition to any centralized leadership taking control of the development of the Classic chain specifically by the foundation. That we are not against individual developers from the foundation working on the classic chain, only centralized leadership coming from them.  

We should highlight the values that give money value. That while Dapps and Smart contracts are important features and we look forward on improving them. That the most important purpose of Ethereum Classic is that it is a decentralized peer to peer cash system modeled after Bitcoin created by Satoshi Nakamoto.

**Comment by realcodywburns** [comment]
It seems you have the idea for the basic frame work of the document in place.

**Comment by whatisgravity** [comment]
@ChuckSRQ I agree with most of that, would you be interested in writing a more formal rough draft?

**Comment by ChuckSRQ** [comment]
@whatisgravity A group has been formed on slack it.. A rough draft is being worked on.

**Comment by ProphetDaniel** [comment]
Thank you all for the great whitepapers produced!
