### ISSUE TITLE
Proposal to refer to ETC coins as "ethcoin(s)" instead of ether.... 

### ISSUE THREAD

**Issue by cseberino** [ethereumclassic/README#36]
(I put this on reddit sub as well.  Wasn't sure where it should go so crossposting.  Hope that's ok.)

To distinguish currency of ETH from the currency of ETC it may be a good idea to refer to the currency of ETC as "ethcoin" or "ethcoins".
This has the added benefit that it corresponds nicely to the acronym ETC.
(Bitcoin, Ethcoin, .....has a nice ring to it.)
What does everyone think?

**Comment by arvicco** [comment]
ETC branding discussions: https://trello.com/b/ziFiVzAc/etc-branding-identity
