### ISSUE TITLE
Organization video

### ISSUE THREAD

**Issue by ProphetDaniel** [ethereumclassic/README#43]
Now that most value proposition [whitepapers](https://github.com/ethereumclassic/README/issues/33) are ready, the production of an organizational vídeo would be very inspiring for the community showing what makes of Ethereum Classic unique and the future of smart contracts technology.

**Comment by ProphetDaniel** [comment]
We have also the opportunity to encode vídeos of the [scrolling Declaration of Independence](https://github.com/ethereumclassic/DeclarationOfIndependence).

**Comment by arvicco** [comment]
Promotional videos:
https://www.youtube.com/watch?v=wOxwuoJaJXc (English voiceover)
https://www.youtube.com/watch?v=a_3eim44Qpk (Russian voiceover)
https://www.youtube.com/watch?v=hg3nH5pmqhI (No voiceover, add your own)
