### ISSUE TITLE
Ethereum Classic Group at Linkedin is not from our community

### ISSUE THREAD

**Issue by ProphetDaniel** [ethereumclassic/README#44]
The LinkedIn group entitled ["Ethereum Classic - the original and unforked one"](https://www.linkedin.com/groups/6729915/
) does not represent the community and could present a threat to Ethereum Classic.
<a href="http://imgur.com/1Bw22jq"><img src="http://i.imgur.com/1Bw22jq.png" title="source: imgur.com" /></a>

An Ethereum Classic LinkedIn group was created today with name "Ethereum Classic" to defend against moves like this and make sure the community has social networks presence:
[Ethereum Classic](https://www.linkedin.com/groups/12000492)

Possible attack came through IRC channel and was delivered to the slack by the integration bot.
<a href="http://imgur.com/jJ0PPzF"><img src="http://i.imgur.com/jJ0PPzF.png" title="source: imgur.com" /></a>

**Comment by ProphetDaniel** [comment]
The selection of community members to administrate the group will be carefully made. Thank you.

**Comment by Foundups** [comment]
**Beware of False Prophet?** @ProphetDaniel  
Listen to my talk https://www.youtube.com/watch?v=Om1BJ8Ce6Xo
New Talk https://youtu.be/Z0JYOcANn24

**Comment by ProphetDaniel** [comment]
@Foundups, Some of our first developers are in the group you maintain and after the quarentine has passed, no objection was raised, some posts were even liked. So I believe your Skype call to me today was very important to sort out recent happenings. I admire your enthusiasm toward Ethereum Classic. Welcome aboard and keep pushing.

Both LinkedIn groups are legit and should represent the community. I'm glad with thes outcome of this issue. Cheers, Daniel!

**Comment by Foundups** [comment]
@ProphetDaniel I have no issue with placing anyone as managers. Things are moving fast and your concern is merited. Glad to come to consensus.
