### ISSUE TITLE
Perma throws support behind EthereumClassic

### ISSUE THREAD

**Issue by MrComputerCodes** [ethereumclassic/README#5]
Hello ethereumclassic team,

I spent some time on a clean-slate reboot of the Ethereum project which would be seeded by the hard fork block hash. Links:

https://bitcointalk.org/index.php?topic=1540285.0
https://github.com/permaledger/

We originally considered maintaining a Classic-style fork, but discarded it because we though it was too risky. Well, things change quickly and now we have changed our minds. We now believe our best opportunity to bootstrap a sustainable depoliticized evm ledger is EC.

https://github.com/permaledger/

**Comment by arvicco** [comment]
Great, thanks for your support, guys! 

@MrComputerCodes, who should I send invite to in addition to yourself?

**Comment by whatisgravity** [comment]
Welcome, I started an original/classic fork, for now I believe that is the best solution. I started mining and it seems others have too since the network is continuing to add blocks.
